CenterForOpenScience/osf-cas

- Dockerfile-local
- README.md
[ENG-1886](https://openscience.atlassian.net/browse/ENG-1886)
* Supports [ENG-1887](https://openscience.atlassian.net/browse/ENG-1887)
Update configuration, building and running guide due to recent DevOps related update.
* Updated links due to repo change
* Added more detail for database connection and access
* Made an effort to separate local development and server deployment
* Updated `Dockerfile-run` with more explanation
With this updated guide, developers should be able to setup and run CAS locally with OSF.
N / A
N / A
> [ENG-1886] Update Config / Build / Run Guide

- build.gradle
- gradle.properties
- src/main/java/org/apereo/cas/CasTomcatBanner.java
N / A
Customize console title banner
> [No Ticket] Customize Console Title Banner

- src/main/resources/messages.properties
N / A
Fix staging3 links in `messages.properties`
> [No Ticket] Fix Staging3 Links

- etc/cas/config/cas.properties
- etc/cas/config/local/cas-local.properties
N / A
Update Spring security endpoints settings
> [No Ticket] Update Spring Security Endpoints Settings

- src/main/java/io/cos/cas/osf/web/flow/login/OsfDefaultLoginPreparationAction.java
See the diff for details. This is a commit missing from https://github.com/CenterForOpenScience/osf-cas/pull/12
> [No Ticket] Fix Pre Login Check Action

- etc/cas/config/cas.properties
- etc/cas/services/local/casarxiv-203948234207239.json
- src/main/java/io/cos/cas/osf/authentication/exception/InstitutionSsoFailedException.java
- src/main/java/io/cos/cas/osf/authentication/exception/TermsOfServiceConsentRequiredException.java
- src/main/java/io/cos/cas/osf/authentication/support/OsfInstitutionUtils.java
- src/main/java/io/cos/cas/osf/configuration/model/OsfApiProperties.java
- src/main/java/io/cos/cas/osf/configuration/model/OsfUrlProperties.java
- src/main/java/io/cos/cas/osf/model/OsfInstitution.java
- src/main/java/io/cos/cas/osf/web/flow/configurer/OsfCasLogoutWebFlowConfigurer.java
- src/main/java/io/cos/cas/osf/web/flow/login/OsfCasPreInitialFlowSetupAction.java
- src/main/java/io/cos/cas/osf/web/support/OsfApiInstitutionAuthenticationResult.java
No Ticket
Prepare for staging3 deployment
* `since` tag version fix
* `cas.properties` update (for server)
* Registered service definition fix
N / A
N / A
Charts PR: https://github.com/CenterForOpenScience/helm-charts/pull/68
> [No Ticket] Prepare for staging3 deployment

- .github/workflows/build.yml
- build.gradle
No Ticket
Increases our static code analysis for quality and security
Adds sonarqube plugin to grade & github build workflow to support sonarqube 
Configuration changes only
No application changes
SONAR_TOKEN must be configured in the github environment variables
> [No Ticket] Enable SonarQube for newCAS

- .github/workflows/build.yml
- build.gradle
N / A
Fix SonarCube
* Continue Github Action on Sonar Error
* Parameterizes Sonar URL
* Removes parameterized Sonar vars
N / A
N / A
N / A
> Continue Github Action on Sonar Error

- build.gradle
- etc/cas/config/cas.properties
- etc/cas/config/local/cas-local.properties
- etc/cas/config/local/instn-authn-local.xsl
- postman/osf-cas-shib-saml-institution-sso-test.json
- src/main/java/io/cos/cas/osf/web/config/OsfCasSupportActionsConfiguration.java
- src/main/java/io/cos/cas/osf/web/flow/configurer/OsfCasLogoutWebFlowConfigurer.java
- src/main/java/io/cos/cas/osf/web/flow/login/OsfPrincipalFromNonInteractiveCredentialsAction.java
- src/main/java/io/cos/cas/osf/web/flow/support/OsfCasWebflowConstants.java
- src/main/java/org/apereo/cas/web/flow/logout/TerminateSessionAction.java
- src/main/resources/messages.properties
- src/main/resources/templates/error/423.html
- Update: features / improvements in this PR will be released to `feature/newCAS-v21.1.0-beta`
* [ENG-2590](https://openscience.atlassian.net/browse/ENG-2590) - Institution department
* [ENG-2662](https://openscience.atlassian.net/browse/ENG-2662) - Login throttle
* [ENG-2663](https://openscience.atlassian.net/browse/ENG-2663) - Institution customized SLO
Finish up a few left-over tickets was taken out of the scope of previous tickets due to complexity, priority, time-boxing, etc.
* Support the department attribute for institution SSO
* Apply username / IP address based login failure throttling.
* Implement customized logout URL for eligible institutions.
```
[org.apereo.cas.web.flow.logout.TerminateSessionAction] - <Terminated all CAS sessions successfully.> …
```
> [ENG-2590] [ENG-2662] [ENG-2663] newCAS Development Left-overs

- etc/cas/config/local/instn-authn-local.xsl
- src/main/java/io/cos/cas/osf/web/flow/login/OsfPrincipalFromNonInteractiveCredentialsAction.java
https://openscience.atlassian.net/browse/ENG-2683
Fixe issues discovered during testing shared SSO and department attribute
N / A
N / A
N / A
> [ENG-2684] Institution SSO Fixes

- src/main/java/org/apereo/cas/config/CasOAuth20ServicesConfiguration.java
https://openscience.atlassian.net/browse/ENG-2735
Fix a couple of issues revealed during `staging3` OAuth server regression test. See https://www.notion.so/cos/newCAS-Release-Plan-2abd2b47c0e84fc99dd6a93072d9733c and https://www.notion.so/cos/QA-Testing-for-OAuth-2-0-Server-c35edf95ad9c4d099faa4c55606fffd8 for details.
- ~~OAuth session expires if user stays on the login form for too long~~ this will be fixed by [ENG-2736](https://openscience.atlassian.net/browse/ENG-2736)
N / A
N / A
N / A
> [ENG-2735] Fix Banner UI and Disable ORCiD login for Login with OSF

- src/main/java/io/cos/cas/osf/model/OsfOAuth20Pat.java
- src/main/java/org/apereo/cas/support/oauth/web/endpoints/OAuth20UserProfileEndpointController.java
https://openscience.atlassian.net/browse/ENG-2765
Please refer to the ticket for details.
N / A
N / A
N / A
> [ENG-2765] Do Not Validate Deactivated PAT

- README.md
- etc/cas/config/instn-authn-prod.xsl
- src/main/resources/messages.properties
https://openscience.atlassian.net/browse/ENG-1893
Prepare for newCAS prod release:
* Added and updated `instn-authn-prod.xsl` (a faithful local copy to its server counterpart)
* `README.md` up-to-date (w/ a few TODOs ...)
* Fixed minor wording on the institution SSO migration page
N / A
N / A
N / A
> [ENG-1893] Part 2: Prod Server Institution SSO Updates and Other Preparations

- src/main/java/org/apereo/cas/support/oauth/web/endpoints/OAuth20CallbackAuthorizeEndpointController.java
N / A
N / A
N / A
N / A
N / A
N / A
> [No Ticket] Fix OAuth callbackAuthorize URL

- src/main/java/org/apereo/cas/support/oauth/web/endpoints/OAuth20CallbackAuthorizeEndpointController.java
N / A
https://github.com/CenterForOpenScience/osf-cas/pull/41 with https://github.com/CenterForOpenScience/osf-cas/commit/b92b0cb115c65b142d18ceef65e9532383ee800d only fixed one part of the problem by providing the
server-prefixed URL to initialize the `OAuth20CallbackLogic` object. It didn't update the final redirect URL used for the RedirectView.
This is a code-level workaround. We have pinpoint the proper devops-level fix to the Apache shibboleth server.
N / A
N / A
N / A
N / A
> [No Ticket] Fix OAuth callbackAuthorize URL - 3rd Attempt

- src/main/java/org/apereo/cas/support/oauth/web/views/OAuth20ConsentApprovalViewResolver.java
N / A
After https://github.com/CenterForOpenScience/osf-cas/pull/42 successfully fixed the `callbackAuthorize`, a similar issue was surfaced for the approval submission callback URL and thus a similar fix (with a slightly different flavor) has been applied.
N / A
N / A
N / A
N / A
> [No Ticket] Fix OAuth Approval Submission Callback URL

- build.gradle
- gradle.properties
- gradle/springboot.gradle
https://openscience.atlassian.net/browse/ENG-3479
Refer to the ticket
Refer to the diff
N/A
N/A
N/A
> [ENG-3479] Upgrade logger for 6.2.x CAS

- src/main/resources/templates/casInstitutionLoginView.html
- src/main/resources/templates/casUnsupportedInstitutionLoginView.html
- src/main/resources/templates/fragments/header.html
- src/main/resources/templates/fragments/headerosf.html
- src/main/resources/templates/fragments/loginform.html
- src/main/resources/templates/fragments/osfbannerui.html
- src/main/resources/templates/fragments/serviceui.html
https://openscience.atlassian.net/browse/ENG-3492
* Trim "alt" value
* Add missing "alt"
> Is there not a way to identify the specific service as OSF? 
See **Dev Notes**
N/A
> [ENG-3492] 2A & 2AA Follow-up Fixes

- src/main/resources/templates/casInstitutionLoginView.html
- src/main/resources/templates/casUnsupportedInstitutionLoginView.html
- src/main/resources/templates/fragments/loginform.html
- src/main/resources/templates/fragments/totploginform.html
https://openscience.atlassian.net/browse/ENG-4098
Update help links.
For details, refer to the [ticket](https://openscience.atlassian.net/browse/ENG-4098)
* Sign-in help
* Main login page
* Institution login page
* Unsupported institution login page 
* 2FA help
* 2FA page
N/A
N/A
N/A
> [ENG-4098] Update Help Links

- etc/cas/config/cas.properties
- etc/cas/config/local/cas-local.properties
Repo copy update only. For details, refer to the actual update: https://github.com/CenterForOpenScience/helm-charts/pull/82
> Trim institution CAS clients and sync with public charts

- README_OAUTH_SSO_GUIDE.md
CAS part of https://openscience.atlassian.net/browse/ENG-2996
> [ENG-2996] Add OAuth SSO guide

- README_INSTITUTION_SSO_INTEGRATION_GUIDE.md
[ENG-****](https://openscience.atlassian.net/browse/ENG-****)
Typos fixed in lines 55 and 71
Just check the lines 55 and 71 to check the fixes
No special dev notes
No special QA testing notes
No special Dev-operations notes
> "fix/" Typos fixed (lines 55, 71)

- .github/workflows/build.yml
N/A
Fix GitHub action version deprecation
Fix GitHub action version deprecation
N/A
N/A
N/A
> [No Ticket] Fix GitHub action version deprecation
