- src/main/resources/messages.properties
- src/main/resources/static/css/cas.css
- src/main/resources/templates/casAccountDisabledView.html
- src/main/resources/templates/casAccountNotConfirmedIdPView.html
- src/main/resources/templates/casAccountNotConfirmedOsfView.html
- src/main/resources/templates/casGenericSuccessView.html
- src/main/resources/templates/casInstitutionSsoNotImplementedView.html
- src/main/resources/templates/casInvalidUserStatusView.html
- src/main/resources/templates/casInvalidVerificationKeyView.html
- src/main/resources/templates/casLogoutView.html
- src/main/resources/templates/casServiceErrorView.html
- src/main/resources/templates/error.html
- src/main/resources/templates/fragments/footer.html
- src/main/resources/templates/fragments/header.html
- src/main/resources/templates/fragments/osfbannerui.html
- src/main/resources/templates/fragments/pmlinks.html
- src/main/resources/templates/fragments/serviceui.html
- src/main/resources/templates/fragments/submitbutton.html
- src/main/resources/templates/fragments/totploginform.html
- src/main/resources/templates/layout.html
Supports [ENG-2345](https://openscience.atlassian.net/browse/ENG-2345)
* Further customize more error pages
* Improve responsive experience on all error pages
* Updated service error and CAS error page (minor)
* Rewrote generic logout page (minor)
* Rewrote generic login success page (major)
* Fixed OSF logout URL in logout / back-to-OSF buttons 
* Fixed HTML style for a few templates
* Rewrote footer and header
* Improved UI / UX on wide and narrow (width) screens and on short (height) screen experience
* Phone with small screen
* Phone with large screen
* Tablet vertical
* Tablet horizontal
* 720p
* 1080p
* 1440p
N / A
N / A
N / A
> [ENG-2345] Improve responsive experience on error pages

- src/main/resources/static/js/cas.js
Part of https://openscience.atlassian.net/browse/ENG-2345
Fix the issue that the password revealing button doesn't work on mobile devices or in responsive mode as expected.
* Made the feature a **toggle** instead of **mouse up/down** since there is no "counter-part" in responsive mode / on mobile devices. "touch and hold" is usually used / reserved for other built-in purposes which we shouldn't take over.
* This change affects both the password field on the default login page and the one-time password field on the two-factor authentication page.
N / A
N / A
(Please see the description of the testing ticket for details https://openscience.atlassian.net/browse/ENG-2364)
N / A
> [ENG-2345] Fix reveal-password event

- etc/cas/config/cas.properties
- etc/cas/config/local/cas-local.properties
- src/main/java/io/cos/cas/osf/configuration/model/OsfUrlProperties.java
- src/main/java/io/cos/cas/osf/web/config/OsfCasSupportActionsConfiguration.java
- src/main/java/io/cos/cas/osf/web/flow/config/OsfCasWebflowContextConfiguration.java
- src/main/java/io/cos/cas/osf/web/flow/configurer/OsfCasLoginWebflowConfigurer.java
- src/main/java/io/cos/cas/osf/web/flow/configurer/OsfCasLogoutWebFlowConfigurer.java
- src/main/java/io/cos/cas/osf/web/flow/login/OsfAbstractLoginPreparationAction.java
- src/main/java/io/cos/cas/osf/web/flow/login/OsfCasPreInitialFlowSetupAction.java
- src/main/java/io/cos/cas/osf/web/flow/login/OsfPrincipalFromNonInteractiveCredentialsAction.java
- src/main/java/io/cos/cas/osf/web/flow/support/OsfCasWebflowConstants.java
- src/main/java/io/cos/cas/osf/web/support/OsfCasLoginContext.java
- src/main/resources/messages.properties
- src/main/resources/templates/casAutoRedirectToDefaultServiceLoginView.html
- src/main/resources/templates/error/401.html
- src/main/resources/templates/error/403.html
- src/main/resources/templates/error/404.html
- src/main/resources/templates/error/405.html
- src/main/resources/templates/error/423.html
- src/main/resources/templates/fragments/headerflowless.html
- src/main/resources/templates/layoutFlowless.html
N/ A
OSF server-specific settings such as OSF URLs need to be configured at the very beginning of the login flow so that ThymeLeaf templates can be rendered correctly across the flow state machine. Previously, it was configured at the start of the non-interactive action where any rendering attempt before it would fail with empty pages rendered. This is fixed now by overriding the flow init process. A pre-init action with what we did in the non-interactive action before is injected onto the top of the start action list.
HTTP 400 errors are not expected during normal authentication and authorization flow between OSF CAS and OSF. Sometimes they do not trigger login or logout flow init and are handled and routed to built-in templates directly by Tomcat. This unfortunately breaks OSF CAS …
> [No Ticket] Web Flow Pre-init Action

- src/main/java/io/cos/cas/osf/authentication/credential/OsfPostgresCredential.java
- src/main/java/io/cos/cas/osf/authentication/exception/TermsOfServiceConsentRequiredException.java
- src/main/java/io/cos/cas/osf/authentication/handler/support/OsfPostgresAuthenticationHandler.java
- src/main/java/io/cos/cas/osf/authentication/metadata/OsfPostgresAuthenticationMetaDataPopulator.java
- src/main/java/io/cos/cas/osf/model/OsfUser.java
- src/main/java/io/cos/cas/osf/web/flow/config/OsfCasCoreWebflowConfiguration.java
- src/main/java/io/cos/cas/osf/web/flow/configurer/OsfCasLoginWebflowConfigurer.java
- src/main/java/io/cos/cas/osf/web/flow/support/OsfCasWebflowConstants.java
- src/main/resources/messages.properties
- src/main/resources/static/css/cas.css
- src/main/resources/templates/casInstitutionLoginView.html
- src/main/resources/templates/casTermsOfServiceConsentView.html
- src/main/resources/templates/casTwoFactorLoginView.html
- src/main/resources/templates/fragments/loginform.html
- src/main/resources/templates/fragments/submitbutton.html
- src/main/resources/templates/fragments/tosloginform.html
- src/main/resources/templates/fragments/totploginform.html
[ENG-2442](https://openscience.atlassian.net/browse/ENG-2442)
* OSF side supporting PR: https://github.com/CenterForOpenScience/osf.io/pull/9595
Implement terms of service consent check in `newCAS`.
* Institution users no longer need to check the consent checkbox every time. Only users that haven't agreed before will see a dedicated page for them to agree to the terms.
* When OSF updates terms of service, all users will be required to agree to the new terms upon login.
* Updated login web flow to support the new user consent feature
* Inform OSF of user's terms of service consent via attribute release
* Removed front-end check on the institution login page
* Updated submit button and related pages
N / A
Please refer to the ticket. Given that institution SSO is not available on staging3, …
> [ENG-2442] Terms of service consent check

- gradle.properties
Update CAS overlay template to use the latest `6.2.x`.
* The overlay template has 6.2.6, which is slightly out-dated compared to the primary library. However, local testing hasn't reviewed any issues so far, and thus newCAS uses 6.2.8 now.
* All OAuth 2.0 (server) features are implemented on top of 6.2.8. There are several non-trivial changes in 6.3.x, thus we decided to stick with 6.2.x for the initial full implementation.
* References
* Apereo CAS library version: https://github.com/apereo/cas/tree/v6.2.8
* Apereo CAS overlay template version: https://github.com/apereo/cas-overlay-template/commits/6.2
> [No Ticket] Update from 6.2.1 to 6.2.8

- etc/cas/config/cas.properties
- etc/cas/config/local/cas-local.properties
- src/main/java/io/cos/cas/oauth/support/OsfCasOAuth20Utils.java
- src/main/java/org/apereo/cas/config/CasOAuth20Configuration.java
- src/main/java/org/apereo/cas/config/CasOAuth20ServicesConfiguration.java
https://openscience.atlassian.net/browse/ENG-2661
Fixed an overlay bug discovered during DevQA where Spring configuration classes somehow fail to pick up overlaid interface constants.
Updated local and server properties for the OAuth server.
See **Purpose**.
N / A
N / A
N / A
> [ENG-2661] OAuth Server Fixes

- src/main/resources/messages.properties
- src/main/resources/static/css/cas.css
- src/main/resources/templates/casAccountDisabledView.html
- src/main/resources/templates/casAccountNotConfirmedIdPView.html
- src/main/resources/templates/casAccountNotConfirmedOsfView.html
- src/main/resources/templates/casGenericSuccessView.html
- src/main/resources/templates/casInstitutionLoginView.html
- src/main/resources/templates/casInstitutionSsoFailedView.html
- src/main/resources/templates/casInvalidUserStatusView.html
- src/main/resources/templates/casInvalidVerificationKeyView.html
- src/main/resources/templates/casLogoutView.html
- src/main/resources/templates/casOAuth20ErrorView.html
- src/main/resources/templates/casServiceErrorView.html
- src/main/resources/templates/casUnsupportedInstitutionLoginView.html
- src/main/resources/templates/error.html
- src/main/resources/templates/error/401.html
- src/main/resources/templates/error/403.html
- src/main/resources/templates/error/404.html
- src/main/resources/templates/error/405.html
- src/main/resources/templates/error/423.html
- src/main/resources/templates/fragments/loginform.html
- src/main/resources/templates/fragments/tosloginform.html
- src/main/resources/templates/fragments/totploginform.html
- src/main/resources/templates/protocol/oauth/confirm.html
https://openscience.atlassian.net/browse/ENG-2720
Polish front-end according to demo and QA feed back (5th round). See https://www.notion.so/cos/newCAS-Release-Plan-2abd2b47c0e84fc99dd6a93072d9733c for details.
- ~~Disable submit buttons input for all eligible pages~~ This fix will be moved to its own ticket [ENG-2753](https://openscience.atlassian.net/browse/ENG-2753).
N / A
N / A
N / A
> [ENG-2720] Front-end Polishing (a.k.a Demo / QA Response)

- src/main/java/org/apereo/cas/support/oauth/web/endpoints/OAuth20AuthorizeEndpointController.java
https://openscience.atlassian.net/browse/ENG-2763
Expected behavior: invalid / empty `access_type` is ignored and the default value `ONLINE` is used
Actual behavior: invalid / empty `access_type` crashes the server during authorization approval
See reviews in code diff.
N / A
N / A
> [ENG-2763] Fix Invalid Access Type

- src/main/resources/templates/casAccountDisabledView.html
- src/main/resources/templates/casAccountNotConfirmedIdPView.html
- src/main/resources/templates/casAccountNotConfirmedOsfView.html
- src/main/resources/templates/casGenericSuccessView.html
- src/main/resources/templates/casInstitutionLoginView.html
- src/main/resources/templates/casInstitutionSsoFailedView.html
- src/main/resources/templates/casInvalidUserStatusView.html
- src/main/resources/templates/casInvalidVerificationKeyView.html
- src/main/resources/templates/casLoginView.html
- src/main/resources/templates/casLogoutView.html
- src/main/resources/templates/casOAuth20ErrorView.html
- src/main/resources/templates/casServiceErrorView.html
- src/main/resources/templates/casTermsOfServiceConsentView.html
- src/main/resources/templates/casTwoFactorLoginView.html
- src/main/resources/templates/casUnsupportedInstitutionLoginView.html
- src/main/resources/templates/error.html
- src/main/resources/templates/error/401.html
- src/main/resources/templates/error/403.html
- src/main/resources/templates/error/404.html
- src/main/resources/templates/error/405.html
- src/main/resources/templates/error/423.html
- src/main/resources/templates/fragments/header.html
- src/main/resources/templates/fragments/headerosf.html
- src/main/resources/templates/layoutosf.html
- src/main/resources/templates/protocol/oauth/confirm.html
https://openscience.atlassian.net/browse/ENG-2736
Customized OSF CAS pages now use the customized layout and header that are aware of the OSF context; the rest, both customized and built-in Apereo CAS pages have switched to use the default layout and header. This solves the issue that a built-in page is rendered using the customized layout without knowing the context.out without knowing the context.
N / A
N / A
N / A
> [ENG-2736] Swap Flow-aware and Flow-unaware Templates

- src/main/resources/templates/casAccountDisabledView.html
- src/main/resources/templates/casAccountNotConfirmedIdPView.html
- src/main/resources/templates/casAccountNotConfirmedOsfView.html
- src/main/resources/templates/casGenericSuccessView.html
- src/main/resources/templates/casInstitutionLoginView.html
- src/main/resources/templates/casInstitutionSsoFailedView.html
- src/main/resources/templates/casInvalidUserStatusView.html
- src/main/resources/templates/casInvalidVerificationKeyView.html
- src/main/resources/templates/casLoginView.html
- src/main/resources/templates/casLogoutView.html
- src/main/resources/templates/casOAuth20ErrorView.html
- src/main/resources/templates/casServiceErrorView.html
- src/main/resources/templates/casTermsOfServiceConsentView.html
- src/main/resources/templates/casTwoFactorLoginView.html
- src/main/resources/templates/casUnsupportedInstitutionLoginView.html
- src/main/resources/templates/error.html
- src/main/resources/templates/error/401.html
- src/main/resources/templates/error/403.html
- src/main/resources/templates/error/404.html
- src/main/resources/templates/error/405.html
- src/main/resources/templates/error/423.html
- src/main/resources/templates/fragments/header.html
- src/main/resources/templates/fragments/headerosf.html
- src/main/resources/templates/fragments/tosloginform.html
- src/main/resources/templates/fragments/totploginform.html
- src/main/resources/templates/layoutosf.html
- src/main/resources/templates/protocol/oauth/confirm.html
https://openscience.atlassian.net/browse/ENG-2782
newCAS’s nav-bar (top-bar) has a green sign-up button on the right side. However, this sign-up button is not always relevant during the login process. The following two pages need to have this page disabled.
* Two-factor login page
* Terms of service consent page
* Call `disableSignUpButton()` on both pages. See https://github.com/CenterForOpenScience/osf-cas/pull/32/commits/5b7a1e383023f0079f73b13aed128d223ac6faf6.
* In addition, added missing scripts on the `header.html`. See https://github.com/CenterForOpenScience/osf-cas/pull/32/commits/28b0b74a2b1db41435cdb67741055c86ac54fee9. This is the default flow-unaware one that doesn't affect the two pages in this PR.
N / A
N / A
N / A
> [ENG-2782] Disable Sign-up Button on the TOS consent and 2FA Page

- src/main/resources/messages.properties
- src/main/resources/templates/casAccountDisabledView.html
- src/main/resources/templates/casAccountNotConfirmedIdPView.html
- src/main/resources/templates/casAccountNotConfirmedOsfView.html
- src/main/resources/templates/casGenericSuccessView.html
- src/main/resources/templates/casInstitutionLoginView.html
- src/main/resources/templates/casInstitutionSsoFailedView.html
- src/main/resources/templates/casInvalidUserStatusView.html
- src/main/resources/templates/casInvalidVerificationKeyView.html
- src/main/resources/templates/casLoginView.html
- src/main/resources/templates/casLogoutView.html
- src/main/resources/templates/casOAuth20ErrorView.html
- src/main/resources/templates/casServiceErrorView.html
- src/main/resources/templates/casTermsOfServiceConsentView.html
- src/main/resources/templates/casTwoFactorLoginView.html
- src/main/resources/templates/casUnsupportedInstitutionLoginView.html
- src/main/resources/templates/error.html
- src/main/resources/templates/error/401.html
- src/main/resources/templates/error/403.html
- src/main/resources/templates/error/404.html
- src/main/resources/templates/error/405.html
- src/main/resources/templates/error/423.html
- src/main/resources/templates/fragments/header.html
- src/main/resources/templates/fragments/headerosf.html
- src/main/resources/templates/fragments/tosloginform.html
- src/main/resources/templates/fragments/totploginform.html
- src/main/resources/templates/layoutosf.html
- src/main/resources/templates/protocol/oauth/confirm.html
https://openscience.atlassian.net/browse/ENG-2783
"/error" is the end view state whenever an unexpected and unhandled exception occurs, which can be triggered in both web flows that are aware or unaware of the OSF. Thus, the template must use the default layout and header to avoid rendering issues when the OSF is not in context (though the chance is quite low).
In addition, URLs on this page have been updated to redirect users back to OSF-aware pages so that they can navigate back to the OSF or login again with the OSF as the service.
See **Purpose** and https://github.com/CenterForOpenScience/osf-cas/pull/33/commits/c2f48115a6570ccf305ab90247203fcff4db3d2f.
N / A
N / A
N / A
> [ENG-2783] Flow-unaware Server Error Page

- src/main/resources/messages.properties
- src/main/resources/static/css/cas.css
- src/main/resources/templates/casAccountDisabledView.html
- src/main/resources/templates/casAccountNotConfirmedIdPView.html
- src/main/resources/templates/casAccountNotConfirmedOsfView.html
- src/main/resources/templates/casGenericSuccessView.html
- src/main/resources/templates/casInstitutionLoginView.html
- src/main/resources/templates/casInstitutionSsoFailedView.html
- src/main/resources/templates/casInvalidUserStatusView.html
- src/main/resources/templates/casInvalidVerificationKeyView.html
- src/main/resources/templates/casLoginView.html
- src/main/resources/templates/casLogoutView.html
- src/main/resources/templates/casOAuth20ErrorView.html
- src/main/resources/templates/casServiceErrorView.html
- src/main/resources/templates/casTermsOfServiceConsentView.html
- src/main/resources/templates/casTwoFactorLoginView.html
- src/main/resources/templates/casUnsupportedInstitutionLoginView.html
- src/main/resources/templates/error.html
- src/main/resources/templates/error/401.html
- src/main/resources/templates/error/403.html
- src/main/resources/templates/error/404.html
- src/main/resources/templates/error/405.html
- src/main/resources/templates/error/423.html
- src/main/resources/templates/fragments/header.html
- src/main/resources/templates/fragments/headerosf.html
- src/main/resources/templates/fragments/tosloginform.html
- src/main/resources/templates/fragments/totploginform.html
- src/main/resources/templates/layoutosf.html
- src/main/resources/templates/protocol/oauth/confirm.html
https://openscience.atlassian.net/browse/ENG-2781
Disable developer mode on the CAS Unavailable page and the generic login success page
* Removed the stack trace and the show-hide button.
* Moved error code, message and timestamp to the standard output.
* Added initiator request URL to the standard output
* Restyled error display
* Removed detailed attributes and show-hide button
* Moved a few attributes (email, names, OSF user GUID and CAS principal ID) to the standard output
* Added UTC timestamp
* Restyled attributes display
* Restyled page tips
* Restyled page tips
N / A
N / A
N / A
> [ENG-2781] Disable Developer Mode W/ Minor Improvements

- src/main/java/org/apereo/cas/config/CasWebAppConfiguration.java
https://openscience.atlassian.net/browse/ENG-2798
Solve the root cause for the relative redirect issue mentioned in https://github.com/CenterForOpenScience/osf-cas/pull/37
Overlay `CasWebAppConfiguration` and append server name to the redirect URL.
N / A
N / A
N / A
> [ENG-2798] Fix Root Controller Relative Redirect

- src/main/java/org/apereo/cas/config/CasOAuth20Configuration.java
https://openscience.atlassian.net/browse/ENG-2798
Similar to https://github.com/CenterForOpenScience/osf-cas/pull/39, this PR fixes the relative redirect issue for the `callbackAuthorize` Controller.
The root cause is not fixed, which is likely to be the Apache server or the ingress controller on staging 1 and prod.
N / A
N / A
N / A
N / A
> [ENG-2798] Fix the Relative Redirect Issue for callbackAuthorize Controller 

- src/main/java/io/cos/cas/osf/web/flow/login/OsfInstitutionLoginPreparationAction.java
- src/main/resources/templates/casInstitutionLoginView.html
https://openscience.atlassian.net/browse/ENG-2825
Institution SSO doesn't work for `cas-pac4j` institutions on `prod`.
* Go to institution login for Concordia https://accounts.osf.io/login?campaign=institution&institutionId=cord&service=https://osf.io/login/?next%3Dhttps%253A%252F%252Fosf.io%252F
* Click the sign-in button and the login flow ends up on this page https://accounts.osf.io/null with 403
The root cause is that login URLs weren't set for such institutions in the FE template.
Set / fixed the URLs
N / A
N / A
N / A
> [ENG-2825] Fix CAS-PAC4J Institution SSO login URL

- build.gradle
https://openscience.atlassian.net/browse/ENG-2826
Concordia login failed due to the class [Saml11TicketValidator](https://github.com/apereo/java-cas-client/blob/cas-client-3.6.1/cas-client-support-saml/src/main/java/org/jasig/cas/client/validation/Saml11TicketValidator.java) not found. Unlike the `fakeCAS` IdP that is used for local testing, `cord` and `okstate` use this SAML validator instead of the built-in CAS validator.
As mentioned in [java-cas-client#components](https://github.com/apereo/java-cas-client#components), newCAS needs an extra dependency in addition to the core module.  
```xml
<dependency>
<groupId>org.jasig.cas.client</groupId>
<artifactId>cas-client-support-saml</artifactId>
<version>${java.cas.client.version}</version>
</dependency>
```
Updated `gradle` dependencies …
> [ENG-2826] Supports SAML Validation for PAC4J CAS Client

- src/main/java/io/cos/cas/osf/dao/JpaOsfDao.java
- src/main/java/io/cos/cas/osf/model/OsfInstitution.java
https://openscience.atlassian.net/browse/ENG-2905
Add a property to the `OsfInstitution` model to read the new `deactivated` field added by [ENG-2904](https://openscience.atlassian.net/browse/ENG-2905) ( [OSF-PR#9703](https://github.com/CenterForOpenScience/osf.io/pull/9703)).
* Added a field to the institution model to indicate whether the institution has been deactivated.
* Updated the data access object to filter out deactivated institutions. 
N / A
N / A
> [ENG-2905] Update the institution model and data access object to support deactivated institutions

- gradle.properties
https://openscience.atlassian.net/browse/ENG-3479
Bump log4j from 2.15.0 to 2.16.0 according to [log4j](https://logging.apache.org/log4j/2.x/security.html).
> It was found that the fix to address CVE-2021-44228 in Apache Log4j 2.15.0 was incomplete in certain non-default configurations. When the logging configuration uses a non-default Pattern Layout with a Context Lookup (for example, $${ctx:loginId}), attackers with control over Thread Context Map (MDC) input data can craft malicious input data using a JNDI Lookup pattern, resulting in an information leak and remote code execution in some environments and local code execution in all environments; remote code execution has been demonstrated on macOS but no other tested environments.
In addition, …
> [ENG-3479] Another logger upgrade for CAS 6.2.x

- src/main/resources/messages.properties
- src/main/resources/templates/fragments/footer.html
https://openscience.atlassian.net/browse/ENG-3501
We are in 2022! Bump copyright year ... and make the update automatic from now on.
Spring somehow decides to format number by adding commas, which must be a format setting somewhere.
Must add `.toString()` in the template to mitigate that.
N/A
> [ENG-3501] Automatically bump copyright year

- src/main/resources/static/css/cas.css
- src/main/resources/templates/casAccountDisabledView.html
- src/main/resources/templates/casAccountNotConfirmedIdPView.html
- src/main/resources/templates/casAccountNotConfirmedOsfView.html
- src/main/resources/templates/casGenericSuccessView.html
- src/main/resources/templates/casInstitutionLoginView.html
- src/main/resources/templates/casInstitutionSsoFailedView.html
- src/main/resources/templates/casInvalidUserStatusView.html
- src/main/resources/templates/casInvalidVerificationKeyView.html
- src/main/resources/templates/casLogoutView.html
- src/main/resources/templates/casOAuth20ErrorView.html
- src/main/resources/templates/casPac4jStopWebflow.html
- src/main/resources/templates/casServiceErrorView.html
- src/main/resources/templates/casUnsupportedInstitutionLoginView.html
- src/main/resources/templates/error.html
- src/main/resources/templates/error/401.html
- src/main/resources/templates/error/403.html
- src/main/resources/templates/error/404.html
- src/main/resources/templates/error/405.html
- src/main/resources/templates/error/423.html
- src/main/resources/templates/fragments/loginform.html
- src/main/resources/templates/fragments/osfbannerui.html
- src/main/resources/templates/fragments/serviceui.html
- src/main/resources/templates/fragments/submitbutton.html
- src/main/resources/templates/fragments/tosloginform.html
- src/main/resources/templates/fragments/totploginform.html
- src/main/resources/templates/layout.html
- src/main/resources/templates/layoutosf.html
- src/main/resources/templates/protocol/oauth/confirm.html
* https://openscience.atlassian.net/browse/ENG-2975
* https://openscience.atlassian.net/browse/ENG-3043
* https://openscience.atlassian.net/browse/ENG-3046
* https://openscience.atlassian.net/browse/ENG-3049
* https://openscience.atlassian.net/browse/ENG-3051
* https://openscience.atlassian.net/browse/ENG-3054
* https://openscience.atlassian.net/browse/ENG-3057
* Remove redundant `role="main"` in the `<main>` tag.
* Fix order / semantics for the heading tags
~~As for heading tag order / semantics, current solution is adding empty ones.~~
```html
<h1></h1>
<h2 th:text="#{screen.oauth.confirm.header}" />
<h3></h3>
<h4 th:text="#{screen.oauth.confirm.message}" />
```
**Update**: the above approach has been replaced with a better alternative, which overrides heading tags so …
> [ENG-2975][ENG-3043][ENG-3046][ENG-3049][ENG-3051][ENG-3054][ENG-3057] A11y Best Practice Fixes

- src/main/resources/templates/fragments/loginform.html
- src/main/resources/templates/fragments/totploginform.html
https://openscience.atlassian.net/browse/ENG-3544
Fix `autocomplete` for the password and one-time code input fields
Please refer to the [ticket](https://openscience.atlassian.net/browse/ENG-3544)
N/A
* In addition to Firefox, Safari isn't affected by this bug either.
N/A
> [ENG-3544] Fix autocomplete for password and one-time code input fields

- etc/cas/config/local/instn-authn-local.xsl
- src/main/java/io/cos/cas/osf/authentication/exception/InstitutionSelectiveSsoFailedException.java
- src/main/java/io/cos/cas/osf/authentication/support/OsfApiPermissionDenied.java
- src/main/java/io/cos/cas/osf/web/flow/config/OsfCasCoreWebflowConfiguration.java
- src/main/java/io/cos/cas/osf/web/flow/configurer/OsfCasLoginWebflowConfigurer.java
- src/main/java/io/cos/cas/osf/web/flow/login/OsfPrincipalFromNonInteractiveCredentialsAction.java
- src/main/java/io/cos/cas/osf/web/flow/support/OsfCasWebflowConstants.java
- src/main/resources/messages.properties
- src/main/resources/templates/casInstitutionSelectiveSsoFailedView.html
[ENG-3507](https://openscience.atlassian.net/browse/ENG-3507)
[ENG-3508](https://github.com/CenterForOpenScience/osf.io/pull/9877/files) with [PR-OSF#9877](https://github.com/CenterForOpenScience/osf.io/pull/9877)
Implement selective SSO for institution login.
* Updated class `OsfPrincipalFromNonInteractiveCredentialsAction` to support institution selective SSO.
* Reworked API response handling to identify selective SSO failures
* Updated the web flow with new exception and error page
* Flattened the convoluted control flow for handling institution SSO failures
* Make `try {} catch {}` blocks finder-grained 
* Reworked local Postman tests
* Updated `instn-authn-local.xsl` to support new tests.
N/A
This can only be tested by institution parters. Here is the new error page.
Although this PR …
> [ENG-3507] Institution Selective SSO - CAS Part

- src/main/java/io/cos/cas/osf/authentication/support/DelegationProtocol.java
- src/main/java/io/cos/cas/osf/authentication/support/OsfInstitutionUtils.java
- src/main/resources/templates/casInstitutionLoginView.html
https://openscience.atlassian.net/browse/ENG-3623
Update CAS to support institutions of which SSO and affiliation is done via ORCiD.
We've chosen the balanced solution out the three in the ticket.
* CAS list `via-orcid` institutions in the drop-down list with extra note "via ORCiD SSO" appended as suffix.
* When clicked, it redirects user to ORCiD login and the rest follow standard ORCiD login flow
* Affiliation is done in OSF and thus out of the scope of this PR
https://user-images.githubusercontent.com/3750414/155822339-eab7a559-4b61-4f33-8831-96aa7122d13a.mov
N/A
- QA notes will be updated when the full feature is ready for test
- ~~This PR can be merged without its OSF part: https://github.com/CenterForOpenScience/osf.io/pull/9888. The new feature simply won't take effect until OSF is …
> [ENG-3623] Support via-ORCiD Institutions

- build.gradle
- etc/cas/config/cas.properties
- etc/cas/config/local/cas-local.properties
Support https://openscience.atlassian.net/browse/ENG-3773
CAS doesn't not have a status endpoint for health check, which led up to K8s liveness probing using the login endpoint.
We suspect this is what has been causing the CAS pod restarting since the login endpoint may take a while to load. Thus, this PR enables the `/actuator/health` endpoint.
Without detail, it returns HTTP 200 OK with
```json
{
"status": "UP"
}
```
* **Enable** the endpoints as [documented](https://apereo.github.io/cas/6.2.x/monitoring/Monitoring-Statistics.html#cas-endpoints)
* **Configure** the endpoints
```yaml
management.endpoints.web.exposure.include=health
management.endpoint.health.enabled=true
management.endpoint.health.show-details=WHEN_AUTHORIZED
cas.monitor.endpoints.endpoint.health.access=ANONYMOUS
```
* …
> [ENG-3773] Enable CAS health endpoint for K8s probing

- etc/cas/config/cas.properties
- etc/cas/config/local/cas-local.properties
- src/main/java/io/cos/cas/oauth/ticket/support/OsfCasOAuth20PersonalAccessTokenExpirationPolicy.java
- src/main/java/org/apereo/cas/support/oauth/web/endpoints/OAuth20UserProfileEndpointController.java
Support https://openscience.atlassian.net/browse/ENG-3773
* Fix postgres insertion error / lock due to CAS PAT artificially expiring in CAS DB.
* newCAS creates an artificial expiration date (1 year) for PATs while OSF keeps PATs forever. From CAS DB's perspective, PATs inherits from AT, which inherits from ticket. They all use the same design where the ticket/token ID is actually the primary key `id`. Our guess is that the weird locking/integrity issue happens when the same PAT is inserted before the old PAT gets vacuumed or deleted. Thus the fix is to update the expiration policy to never-expire in order to avoid the above glitch. This, in fact, reverts the expiration policy to [what oldCAS did](https://github.com/CenterForOpenScience/cas-overlay/blob/develop/cas-server-support-oauth/src …
> [ENG-3773] Update CAS PAT to the same Never-Expire as OSF PAT

- src/main/java/io/cos/cas/osf/authentication/support/DelegationProtocol.java
- src/main/java/io/cos/cas/osf/authentication/support/OsfInstitutionUtils.java
- src/main/resources/templates/casInstitutionLoginView.html
Epic: https://openscience.atlassian.net/browse/ENG-3619
Ticket: https://openscience.atlassian.net/browse/ENG-3623
(Replaces https://github.com/CenterForOpenScience/osf-cas/pull/61)
Update CAS to support institutions of which SSO and affiliation is done via ORCiD.
We've chosen the balanced solution out the three in the ticket.
* CAS list `via-orcid` institutions in the drop-down list with extra note "via ORCiD SSO" appended as suffix.
* When clicked, it redirects user to ORCiD login and the rest follow standard ORCiD login flow
* Affiliation is done in OSF and thus out of the scope of this PR
N/A
Refer to the Backend/OSF PR.
> [ENG-3619] Institution Affiliation via ORCiD SSO - CAS Part

- src/main/java/io/cos/cas/osf/web/flow/login/OsfPrincipalFromNonInteractiveCredentialsAction.java
Supports: https://openscience.atlassian.net/browse/ENG-3654
Primary OSF PR: https://github.com/CenterForOpenScience/osf.io/pull/9977
Update shared SSO to support `userRoles`
Changes in this PR do not block the shared SSO feature update since the only code change is log updates. The actual  changes are the attribute mapping (Shibboleth) and normalization (CAS) updates, both of which live in private server settings. Refer to DevOps Notes for details.
```xml
<xsl:when test="$idp='https://idp.fsu.edu'">
<id>fsu</id>
<user>
<username><xsl:value-of select="//attribute[@name='mail']/@value"/></username>
<userRoles><xsl:value-of select="//attribute[@name='userroles']/@value"/></userRoles>
<fullname><xsl:value-of select="//attribute[@name='displayname']/@value"/></fullname>
<familyName/> …
```
> [ENG-3654] Update shared SSO to support userRoles

- README.md
- etc/cas/config/cas.properties
- etc/cas/config/instn-authn-prod.xsl
- etc/cas/config/instn-authn-test.xsl
- etc/cas/config/local/cas-local.properties
- etc/cas/services/local/casarxiv-203948234207239.json
- etc/cas/services/local/osf-203948234207230.json
- etc/cas/services/local/preprints-203948234207240.json
- etc/cas/services/local/registries-203948234207340.json
- src/main/java/io/cos/cas/osf/web/flow/login/OsfPrincipalFromNonInteractiveCredentialsAction.java
- src/main/resources/templates/casInstitutionLoginView.html
https://openscience.atlassian.net/browse/ENG-4178
OKState SSO Protocol Change: CAS -> SAML
- OSF PR: https://github.com/CenterForOpenScience/osf.io/pull/10108
- Helm Charts PR: https://github.com/CenterForOpenScience/helm-charts/pull/81
* [Sync prod and test instn-authn.xsl between repo and helm charts](https://github.com/CenterForOpenScience/osf-cas/commit/e3014283b2d9a8eff30a0773fa2d20ab0f8635b0)
* [Fix local OSFI CAS SSO: rename fakecas to osftype0](https://github.com/CenterForOpenScience/osf-cas/commit/c4d368454c5fc4b25654a3fc75f5672721da1abf)
* [Migrate OKState SSO from CAS to SAML](https://github.com/CenterForOpenScience/osf-cas/commit/d99fc3e22e8f39748b085cbe3267a9f98bfcb83b)
###
N/A
N/A
Refer to the description of the [OSF …
> [OSFI] [ENG-4178] OKState SSO Protocol Change: CAS -> SAML

- etc/cas/config/instn-authn-prod.xsl
- src/main/java/io/cos/cas/osf/web/flow/login/OsfPrincipalFromNonInteractiveCredentialsAction.java
- src/main/java/io/cos/cas/osf/web/support/OsfApiInstitutionAuthenticationResult.java
See details in https://openscience.atlassian.net/browse/ENG-4191
* `id="email"`
* `id="irismailmainaddress"` (my local copy doesn't have this one though ...)
* `id="uscEmailPrimaryAddress"`.
> [ENG-4191] SSO Patch Part 1: Add an extra check for username and its shibboleth attribute during SSO

- src/main/java/io/cos/cas/osf/authentication/exception/InstitutionSsoOsfApiFailureException.java
- src/main/java/io/cos/cas/osf/web/flow/config/OsfCasCoreWebflowConfiguration.java
- src/main/java/io/cos/cas/osf/web/flow/configurer/OsfCasLoginWebflowConfigurer.java
- src/main/java/io/cos/cas/osf/web/flow/login/OsfPrincipalFromNonInteractiveCredentialsAction.java
- src/main/java/io/cos/cas/osf/web/flow/support/OsfCasWebflowConstants.java
- src/main/resources/messages.properties
- src/main/resources/templates/casInstitutionOsfApiFailureView.html
https://openscience.atlassian.net/browse/ENG-4251
Improve OSF API requests during institution SSO
* Added manual retries for API requests failure due to connection and/or server errors
* Created a new exception flow for the above so that users are properly informed when they encounter such failures
* Added connection and socket timeout for API requests
A few testing logs
```
2022-12-20 10:09:37,258 INFO [io.cos.cas.osf.web.flow.login.OsfPrincipalFromNonInteractiveCredentialsAction] - <[CAS XSLT] All attributes checked: username=user1@type8.osf.io, institution=osftype8>
2022-12-20 10:10:37,283 ERROR [io.cos.cas.osf.web.flow.login.OsfPrincipalFromNonInteractiveCredentialsAction] - <[OSF API] Notify Remote Principal Authenticated Failed - Communication Error: institution=osftype8, …
```
> [ENG-4251] Improve OSF API requests during institution SSO

- src/main/java/io/cos/cas/osf/authentication/credential/OsfPostgresCredential.java
- src/main/java/io/cos/cas/osf/web/flow/login/OsfPrincipalFromNonInteractiveCredentialsAction.java
- src/main/java/io/cos/cas/osf/web/support/OsfApiInstitutionAuthenticationResult.java
Retrieve SSO identity from Shibboleth authn request and send it to OSF API during institution SSO
API Part: https://github.com/CenterForOpenScience/osf.io/pull/10260
Ticket: https://openscience.atlassian.net/browse/ENG-4205 and https://openscience.atlassian.net/browse/ENG-4203
* CAS now releases `ssoEmail` and `ssoIdentity` to OSF API
* It is done in a way that we don't need to update either Shib or CAS attribute mapping for each institution.
* Disambiguate `email/ssoEmail`, `mail/mailOther`, `username`, `eppn` and `remoteUser` and `ssoIdentity`
* Rewrote/updated the SSO flow (SAML/Shibboleth)
* Shibboleth session and attributes parsing
* Initial credential construction from shibboleth
* API payload creation
* Authentication result object
* Final credential update from API result
* …
> [Institution Rework] [ENG-4203] [ENG-4205] Rework Institution SSO flow with identity and affiliation - CAS Part

- src/main/java/io/cos/cas/osf/authentication/support/OsfInstitutionUtils.java
- src/main/java/io/cos/cas/osf/model/OsfInstitution.java
- src/main/java/io/cos/cas/osf/web/config/OsfCasSupportActionsConfiguration.java
- src/main/java/io/cos/cas/osf/web/flow/login/OsfDefaultLoginPreparationAction.java
- src/main/java/io/cos/cas/osf/web/flow/login/OsfInstitutionLoginPreparationAction.java
- src/main/java/io/cos/cas/osf/web/flow/login/OsfPrincipalFromNonInteractiveCredentialsAction.java
- src/main/java/io/cos/cas/osf/web/support/OsfCasLoginContext.java
- src/main/java/io/cos/cas/osf/web/support/OsfCasSsoErrorContext.java
- src/main/resources/messages.properties
- src/main/resources/templates/casInstitutionSsoSelectiveLoginDeniedView.html
https://openscience.atlassian.net/browse/ENG-4436
Blocked by: https://openscience.atlassian.net/browse/ENG-4538
Provide an support email to the users when they fail SSO due to selective SSO rules (if their institution has provided a support email)
* Added `OsfCasSsoErrorContext` to store and send data to the error flow
* Added `JpaOsfDao` access to `OsfPrincipalFromNonInteractiveCredentialsAction`
* Sent data to page via the error context when institution SSO failed
* Added `supportEmail` to `OSFInstitution`
* Provide an support email to the users when they fail SSO due to selective SSO rules (if their institution has provided a support email)
Must be merged and deployed after: https://github.com/CenterForOpenScience/osf.io/pull/10402
N/A (Can't be tested by QA)
> [ENG-4436] Customize SSO Error Handling

- src/main/java/io/cos/cas/osf/authentication/handler/support/OsfPostgresAuthenticationHandler.java
- src/main/java/io/cos/cas/osf/model/OsfTotp.java
https://openscience.atlassian.net/browse/ENG-6082
Fix two-factor authentication after Python 3.12 upgrade
* Supports `totp_secret` in both HEX and plain string format
* Improved exception handling
N/A
* Test existing 2FA works
* Test newly created 2FA works
N/A
> [ENG-6082] Fix two-factor authentication after Python 3.12 upgrade

- src/main/java/io/cos/cas/osf/web/flow/login/OsfPrincipalFromNonInteractiveCredentialsAction.java
https://openscience.atlassian.net/browse/ENG-8792
Force CAS to throw exceptions and display error pages without actually going through the expected web flow.
Supports both `lang.RuntimeException` and `javax.security.auth.login.LoginException`
Force CAS to throw exceptions and display error pages without actually going through the expected web flow.
N/A
N/A
N/A
> [ENG-8792] Force CAS to throw exceptions and display error pages

- src/main/resources/static/css/cas.css
- src/main/resources/templates/casAccountDisabledView.html
- src/main/resources/templates/casAccountNotConfirmedIdPView.html
- src/main/resources/templates/casAccountNotConfirmedOsfView.html
- src/main/resources/templates/casGenericSuccessView.html
- src/main/resources/templates/casInstitutionSsoAccountInactiveView.html
- src/main/resources/templates/casInstitutionSsoAttributeMissingView.html
- src/main/resources/templates/casInstitutionSsoAttributeParsingFailedView.html
- src/main/resources/templates/casInstitutionSsoDuplicateIdentityView.html
- src/main/resources/templates/casInstitutionSsoFailedView.html
- src/main/resources/templates/casInstitutionSsoMultipleEmailsNotSupportedView.html
- src/main/resources/templates/casInstitutionSsoOsfApiFailedView.html
- src/main/resources/templates/casInstitutionSsoSelectiveLoginDeniedView.html
- src/main/resources/templates/casInvalidUserStatusView.html
- src/main/resources/templates/casInvalidVerificationKeyView.html
- src/main/resources/templates/casLogoutView.html
- src/main/resources/templates/casPac4jStopWebflow.html
- src/main/resources/templates/casServiceErrorView.html
- src/main/resources/templates/error.html
- src/main/resources/templates/error/401.html
- src/main/resources/templates/error/403.html
- src/main/resources/templates/error/404.html
- src/main/resources/templates/error/405.html
- src/main/resources/templates/error/423.html
* https://openscience.atlassian.net/browse/ENG-8789
* https://openscience.atlassian.net/browse/ENG-8790
* Follow-up for closed ticket https://openscience.atlassian.net/browse/ENG-8791
Rework exception pages, a few examples
OSF Login exception
Institution SSO exception
Http Error
* Remove banner UI
* Remove error tip
* Adjust style
* We get free background and button style from https://github.com/CenterForOpenScience/osf-cas/pull/97 👍 @futa-ikeda 
N/A
N/A
N/A
> [ENG-8789] [ENG-8790] [ENG-8791] Exception Page rework

- etc/cas/config/attribute-map-prod.xml
- etc/cas/config/attribute-map-test.xml
https://openscience.atlassian.net/browse/ENG-8834
Add `eppn` to ADFS attribute set
New `eppn` attribute: `http://schemas.xmlsoap.org/ws/2005/05/identity/claims/eppn`
N/A
N/A
Update server config according to the diff
> [ENG-8834] Add eppn to ADFS attribute set
